version: "3.8"

services:
  server:
    build: ./
    container_name: Server
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: db:5432
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run dev
    restart: on-failure

  db:
    container_name: MusicRoom_DB
    image: postgres
    restart: always
    env_file:
      - ./.env
    #   environment:
    #     POSTGRES_USER: myUsername
    #     POSTGRES_PASSWORD: myPassword
    #     POSTGRES_DB: myProject
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    environment:
      #     PGADMIN_DEFAULT_EMAIL: email@email.com
      #     PGADMIN_DEFAULT_PASSWORD: myPassword
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - 8080:80
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
    logging:
      driver: none

networks:
  default:
    name: MusicRoom-network
